# Generated by Django 4.2.5 on 2023-10-28 15:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "candidate_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(default=" ", max_length=50)),
                ("last_name", models.CharField(default=" ", max_length=50)),
                ("sex", models.CharField(default=" ", max_length=15)),
                ("marital_status", models.CharField(default=" ", max_length=25)),
                ("email", models.EmailField(default=" ", max_length=254, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="+41",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("photo", models.ImageField(default=" ", upload_to="photos/")),
                ("disability", models.CharField(default=" ", max_length=50)),
                ("street", models.CharField(default=" ", max_length=50)),
                ("city", models.CharField(default=" ", max_length=50)),
                ("postal_code", models.CharField(default=" ", max_length=10)),
                ("country", models.CharField(default=" ", max_length=50)),
                ("self_desc", models.TextField(default=" ", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="job",
            fields=[
                ("job_id", models.IntegerField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(default=" ", max_length=50)),
                ("job_position", models.CharField(default=" ", max_length=50)),
                ("company", models.CharField(default=" ", max_length=50)),
                ("job_location", models.CharField(default=" ", max_length=50)),
                ("job_type", models.CharField(default=" ", max_length=50)),
                ("job_desc", models.TextField(default=" ", max_length=100)),
                ("job_role", models.CharField(default=" ", max_length=50)),
                ("job_options", models.CharField(default=" ", max_length=50)),
                ("job_expiry_date", models.DateField(null=True)),
                ("job_exp_of_emp", models.IntegerField(default=0)),
                ("job_sal_expect", models.CharField(default=" ", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_reference",
            fields=[
                ("ref_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ref_name", models.CharField(default=" ", max_length=50)),
                ("ref_Comp", models.CharField(default=" ", max_length=50)),
                ("ref_role", models.CharField(default=" ", max_length=50)),
                ("ref_Date", models.DateField(null=True)),
                ("ref_desc", models.TextField(max_length=100)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_exp",
            fields=[
                ("exp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("curr_comp", models.CharField(default=" ", max_length=50)),
                ("job_title", models.CharField(default=" ", max_length=50)),
                ("skills", models.CharField(default=" ", max_length=50)),
                ("work_desc", models.TextField(max_length=100)),
                ("date_of_joining", models.DateField(null=True)),
                ("date_of_termination", models.DateField(null=True)),
                ("permit", models.CharField(default=" ", max_length=50)),
                ("language", models.CharField(default=" ", max_length=50)),
                ("level", models.CharField(default=" ", max_length=50)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_edu",
            fields=[
                ("edu_id", models.IntegerField(primary_key=True, serialize=False)),
                ("univ", models.CharField(default=" ", max_length=50)),
                ("course", models.CharField(default=" ", max_length=50)),
                ("degree", models.CharField(default=" ", max_length=50)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_Docs",
            fields=[
                ("doc_id", models.IntegerField(primary_key=True, serialize=False)),
                ("doc_name", models.CharField(default=" ", max_length=50)),
                ("doc_data", models.FileField(default=" ", upload_to="resumes/")),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_certification",
            fields=[
                (
                    "certification_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("org_name", models.CharField(default=" ", max_length=100)),
                ("issuing_date", models.DateField(null=True)),
                ("expiry_date", models.DateField(null=True)),
                ("credential_id", models.CharField(default=" ", max_length=100)),
                ("credential_url", models.CharField(default=" ", max_length=100)),
                ("skillset", models.TextField(default=" ", max_length=255)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_application",
            fields=[
                ("app_id", models.IntegerField(primary_key=True, serialize=False)),
                ("app_status", models.CharField(default=" ", max_length=50)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="candidate.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_account",
            fields=[
                ("account_id", models.IntegerField(primary_key=True, serialize=False)),
                ("account_sts", models.CharField(default=" ", max_length=50)),
                ("account_hibernate", models.BooleanField(default=False)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidate",
                    ),
                ),
            ],
        ),
    ]
