POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"lydia1", "password":"test"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"lydia1", "password":"test", "email": "lydia@test.com"}

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token d4199039e26740f14fa2e0029c62c8a4ab5c9178

{}